version: "2.2"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - db_volume:/var/lib/mysql/
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${ACCESS_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PORT=${MARIADB_PORT}
    restart: always
    networks:
      - my_network
    stdin_open: true
    tty: true
  wordpress:
    build: 
      context: ./requirements/wordpress_php/
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp_volume:/var/www/wordpress
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PORT=${MARIADB_PORT}
      - WP_SITE=${WP_SITE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    restart: always
    networks:
      - my_network
    stdin_open: true
    tty: true
  nginx:
    build: 
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - wp_volume:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: always
    stdin_open: true
    tty: true
volumes:
  wp_volume:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "/home/lyie/data/wp_volume"
  db_volume:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "/home/lyie/data/db_volume"
networks: 
  my_network:
